<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/GiftCard
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-gift-card
 */
?>
<?php $storeList = $block->getStoreOptions(); ?>
<!doctype html>
<html lang="en">
    <head>
        <script>
            var FORM_KEY = '<?php echo $block->getFormKey();?>';
        </script>
        <meta charset="utf-8"/>
        <meta name="robots" content="NOINDEX,NOFOLLOW"/>
        <meta name="viewport" content="width=1024"/>
        <meta name="format-detection" content="telephone=no"/>
        <title>MT Editor / Magento Admin / Magento Admin</title>
        <link  rel="icon" type="image/x-icon" href="<?php echo $block->getViewFileUrl('Magento_Theme::favicon.ico'); ?>" />
        <link  rel="shortcut icon" type="image/x-icon" href="<?php echo $block->getViewFileUrl('Magento_Theme::favicon.ico'); ?>" />

        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/bootstrap.min.css'); ?>" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/jquery-ui.css'); ?>" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/jquery.fileupload.css'); ?>" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/mteditor.css'); ?>" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/colorpicker.css'); ?>" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::css/mteditor/popup.css'); ?>" />

        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery-2.1.3.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery-ui.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery.ui.widget.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery.iframe-transport.js"/>'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery.fileupload.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/colorpicker.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/popup.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/jquery.metisMenu.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magetrend_GiftCard::js/mteditor/editor.js'); ?>"></script>

    </head>
<body>
    <div id="editor_wrapper">
        <div class="sidebar">
            <nav class="navbar-default navbar-side" role="navigation">
                <ul class="nav" id="main-menu">
                    <li class="active">
                        <a href="#">
                            <span class="menu-icon glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Edit
                            <span class="glyphicon glyphicon-chevron-right next-level" aria-hidden="true"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li  class="first">
                                <a href="#" class="active open-tools" data-selector="edit-layout">
                                    <span class="menu-icon  glyphicon glyphicon-th-large" aria-hidden="true"></span>
                                    Design
                                </a>
                            </li>
                            <li>
                                <a href="#"  class="open-tools" data-selector="edit-style">
                                    <span class="menu-icon glyphicon glyphicon-tasks" aria-hidden="true"></span>
                                    Color
                                </a>
                            </li>
                            <li>
                                <a href="#"  class="open-tools" data-selector="edit-image">
                                    <span class="menu-icon glyphicon glyphicon-picture" aria-hidden="true"></span>
                                    Background
                                </a>
                            </li>
                            <li>
                                <a href="#"  data-selector="edit-text">
                                    <span class="menu-icon glyphicon glyphicon-asterisk" aria-hidden="true"></span>
                                    Texts
                                </a>
                            </li>
                            <li class="last">
                                <a href="#"  data-selector="edit-size">
                                    <span class="menu-icon glyphicon glyphicon-asterisk" aria-hidden="true"></span>
                                    Other
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <span class="menu-icon glyphicon glyphicon-cog" aria-hidden="true"></span>
                            Actions
                            <span class="next-level glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>

                        <ul class="nav nav-second-level">
                            <li class="first">
                                <a href="#" data-action="change-info">
                                    <span class="menu-icon glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    Change info
                                </a>
                            </li>
                            <li class="last">
                                <a href="#" data-action="delete-template">
                                    <span class="menu-icon glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    Delete template
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div class="actions">
                <button type="button" class="btn btn-complete btn-cons" data-action="save">
                    Save
                </button>
                <button type="button" class="btn btn-default btn-cons" data-action="back" >
                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back to Magento
                </button>
            </div>
        </div>
        <div class="tools edit-layout active">
            <div class="mteditor-panel-scroll">
                <div class="mteditor-panel-container">
                    <div class="tools-container">
                        <div class="title">Select Gift Card Design</div>
                        <div class="block-list">
                            <?php $designList = $block->getDesignList(); ?>
                            <?php foreach ($designList as $design) : ?>
                                <div class="ui-draggable ui-draggable-handle">
                                    <img data-design-code="<?php echo $design['code']; ?>"
                                         class="giftcard-design"
                                         src="<?php echo $block->getViewFileUrl($design['image']);?>"/>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tools edit-style">
            <div class="mteditor-panel-scroll">
                <div class="mteditor-panel-container">
                    <div class="tools-container">
                        <div class="option" style="text-align: center">
                            Change Template Colors
                        </div>
                        <ul>
                            <li id="mtedit_bgcolor">
                                <span>Background & Text</span>
                                <ul></ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="tools edit-text">
            <div class="mteditor-panel-scroll">
                <div class="mteditor-panel-container">
                    <div class="tools-container">
                        <div class="option">
                            <span class="mteditor-option-title">Texts</span>
                            <div class="mteditor-option-container">
                                <div class="form gift-card-text-form" id="giftcard_text">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tools edit-size">
            <div class="empty-panel empty-style-panel">
                There is no any options
            </div>
            <div class="mteditor-panel-scroll data-panel">
                <div class="mteditor-panel-container">
                    <div class="tools-container">
                        <div class="option">
                            <span class="mteditor-option-title">Other Options</span>
                            <div class="mteditor-option-container">
                                <div class="form gift-card-text-form" id="giftcard_size">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tools edit-image">
            <div class="mteditor-panel-scroll">
                <div class="mteditor-panel-container">
                    <div class="tools-container">

                        <div class="mteditor_upload_new">
                            <div class="option">
                                <span class="mteditor-option-title">Upload new image</span>
                                <div class="mteditor-option-container">
                                    <form id="imageupload" action="" method="POST" enctype="multipart/form-data">
                                        <div class="fileupload-buttonbar">
                                            <span class="btn btn-complete btn-cons fileinput-button">
                                                <i class="glyphicon glyphicon-plus"></i>
                                                <span class="mteditor_upload_button">Select image</span>
                                                <input type="file" name="files">
                                            </span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <ul class="mteditor-image-list"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="page-wrapper">
            <div class="scroll-wrapper">
                <div id="email">
                    <div id="giftcard-preview"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="hidden_content">
        <div id="mteditor_tmp"></div>
        <div id="confirm_popup">

            <div class="esns_box_block_1 normal-width">
                <div class="popup-msg"></div>
            </div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Yes</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">No</a> </li>
                </ul>
            </div>
        </div>

        <div id="content_popup">
            <div class="popup-content"></div>

        </div>
        <div id="change_info">
            <div class="popup-form normal-width">

                <div class="form-group">
                    <label><em>*</em>Name</label>
                    <span class="help">e.g. "Design for Luma Store"</span>
                    <input name="name" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label><em>*</em>Store </label>
                    <select class="form-control init-template" name="store_id">

                        <?php foreach ($storeList as $store) : ?>
                            <?php if (is_array($store['value'])) : ?>
                                <optgroup label="<?php echo $block->escapeHtml($store['label']);?>"></optgroup>
                                <?php foreach ($store['value'] as $store2) : ?>
                                    <option  value="<?php echo $block->escapeHtml($store2['value']);?>">
                                        <?php echo $block->escapeHtml($store2['label']);?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif;?>
                            <?php if (is_numeric($store['value'])) : ?>
                                <option  value="<?php echo $block->escapeHtml($store['value']);?>">
                                    <?php echo $block->escapeHtml($store['label']);?>
                                </option>
                            <?php endif;?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="response-error"></div>
            <div class="response-success"></div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Save</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">Cancel</a> </li>
                </ul>
            </div>
        </div>
        <div id="edit_link_form">
            <div class="popup-form normal-width">
                <div class="form-group link-title">
                    <label>Title</label>
                    <span class="help">e.g. "Get it now!"</span>
                    <input name="editor_link_title" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label>Url</label>
                    <span class="help">e.g. "http://www.example.com"</span>
                    <input name="editor_link_href" type="text"  class="form-control">
                </div>
            </div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Apply</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">Remove Link</a> </li>
                </ul>
            </div>
        </div>
        <div id="edit_var_form">
            <div class="popup-form normal-width">
                <div class="form-group link-title">
                    <label>Variables</label>
                    <span class="help">Select one</span>
                    <select name="editor_var" class="form-control"></select>
                </div>
            </div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Insert</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">Cancel</a> </li>
                </ul>
            </div>
        </div>

        <div id="edit_html">
            <div class="popup-form">
                <div class="form-group link-title">
                    <label>HTML editor</label>
                    <textarea name="html" class="form-control big-textarea"></textarea>
                </div>
            </div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Update</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">Cancel</a> </li>
                </ul>
            </div>
        </div>

        <div id="edit_css">
            <div class="popup-form">
                <div class="form-group link-title">
                    <label>Email CSS</label>
                    <textarea name="css" class="form-control big-textarea"></textarea>
                </div>
            </div>
            <div class="popup-actions">
                <ul>
                    <li><a class="btn btn-success btn-cons" href="#" data-action="1">Update</a> </li>
                    <li><a class="btn btn-danger btn-cons" href="#" data-action="0">Cancel</a> </li>
                </ul>
            </div>
        </div>


        <div id="init_new_template">
            <div class="popup-with-form normal-width">
                <div class="popup-form ">
                    <div class="form-group">
                        <label><em>*</em>Name</label>
                        <span class="help">e.g. "Design for Luma Store"</span>
                        <input name="name" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label><em>*</em>Store </label>
                        <select class="form-control init-template" name="store_id">
                            <?php foreach ($storeList as $store) : ?>
                                <?php if (is_array($store['value'])) : ?>
                                    <optgroup label="<?php echo $block->escapeHtml($store['label']);?>"></optgroup>
                                    <?php foreach ($store['value'] as $store2) : ?>
                                        <option  value="<?php echo $block->escapeHtml($store2['value']);?>">
                                            <?php echo $block->escapeHtml($store2['label']);?>
                                        </option>
                                    <?php endforeach; ?>
                                <?php endif;?>
                                <?php if (is_numeric($store['value'])) : ?>
                                    <option  value="<?php echo $block->escapeHtml($store['value']);?>">
                                        <?php echo $block->escapeHtml($store['label']);?>
                                    </option>
                                <?php endif;?>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label><em>*</em>Gift Card Design</label>
                        <select class="form-control init-template" name="design">
                            <option value="">-- -- </option>
                            <?php $designOptions = $block->getDesignList(); ?>
                            <?php foreach ($designOptions as $design) : ?>
                                <option value="<?php echo $block->escapeHtml($design['code']);?>">
                                    <?php echo $block->escapeHtml($design['label']);?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="response-error"></div>
                <div class="popup-actions">
                    <ul>
                        <li>
                            <button class="btn btn-success btn-cons" data-action="1" disabled="disabled">Create New</button>
                        </li>
                        <li>
                            <button class="btn btn-danger btn-cons" data-action="0">Back to Magento</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div id="block-action">
        <ul>
            <li>
                <a href="#" class="block-action-move" title="move"><span class="glyphicon glyphicon-move"></span></a>
            </li>
            <li>
                <a href="#" class="block-action-delete" title="delete" ><span class="glyphicon glyphicon-remove"></span></a>
            </li>
        </ul>
    </div>
    <div id="esns_background_layer">
        <div id="esns_box_layer">
            <div id="esns_box_close"></div>
            <div id="esns_box_content"></div>
        </div>
    </div>

    <div id="editor_helper">
        <div class="helper helper-text">
            <ul>
                <li><a href="#" data-action="bold"><span class="glyphicon glyphicon-bold"></span></a></li>
                <li><a href="#" data-action="italic"><span class="glyphicon glyphicon-italic"></span></a></li>
                <li><a href="#"  data-action="align-left"><span class="glyphicon glyphicon-align-left"></span></a></li>
                <li><a href="#" data-action="align-center"><span class="glyphicon glyphicon-align-center"></span></a></li>
                <li><a href="#" data-action="align-right"><span class="glyphicon glyphicon-align-right"></span></a></li>
                <li><a href="#" data-action="align-justify"><span class="glyphicon glyphicon-align-justify"></span></a></li>
                <li>
                    <a href="#" data-action="link" data-link-type="text"><span class="glyphicon glyphicon-link"></span></a>
                </li>
                <li><a href="#" data-action="var"><span class="text-icon">{{}}</span></a></li>
                <li><a href="#" data-action="html"><span class="text-icon small">HTML</span></a></li>
                <li><a href="#" data-action="image"><span class="glyphicon glyphicon-picture"></span></a></li>
            </ul>
        </div>
        <div class="helper helper-image">
            <ul>
                <li>
                    <a href="#"  data-action="align-left" data-image-editable="true">
                        <span class="glyphicon glyphicon-align-left"></span>
                    </a>
                </li>
                <li>
                    <a href="#" data-action="align-center" data-image-editable="true">
                        <span class="glyphicon glyphicon-align-center"></span>
                    </a>
                </li>
                <li>
                    <a href="#" data-action="align-right" data-image-editable="true">
                        <span class="glyphicon glyphicon-align-right"></span>
                    </a>
                </li>
                <li>
                    <a href="#" data-action="align-justify" data-image-editable="true">
                        <span class="glyphicon glyphicon-align-justify"></span>
                    </a>
                </li>
                <li>
                    <a href="#" data-action="link"  data-link-type="image">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </li>
                <li><a href="#" data-action="remove-image"  data-image-editable="true">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="helper helper-link">
            <ul>
                <li><a href="#" data-action="bold"><span class="glyphicon glyphicon-bold"></span></a></li>
                <li><a href="#" data-action="italic"><span class="glyphicon glyphicon-italic"></span></a></li>
                <li>
                    <a href="#" data-action="link" data-link-type="text">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>


    <div id="loading" style="">
        <span class="loading-animation" style="

        ">Please Wait....</span>
    </div>
</body>
</html>
<?php
//@codingStandardsIgnoreStart
?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        mtEditor.init(<?php echo $this->getJsonConfig(); ?>);
    });
</script>
<?php
//@codingStandardsIgnoreEnd
?>