<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/GiftCard
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-gift-card
 */
?>
<?php $giftCard = $block->getGiftCard(); ?>
<?php if ($giftCard) : ?>
    <?php
        $storeList = $giftCard->getAvailableOnStores();
        $counter = count($storeList);
    ?>
    <?php if ($counter > 0) : ?>
        <?php if ($counter == 1) : ?>
            <?php echo __('The gift card can be used in our store:').' ';?>
        <?php else : ?>
            <?php echo __('The gift card can be used in our stores:').' ';?>
        <?php endif;?>
        <?php foreach ($storeList as $key => $store) : ?>
            <a href="<?php echo  $store['url']; ?>"><?php echo $store['name'];?></a><?php if ($counter-1 != $key) : ?>, <?php endif;?>
        <?php endforeach;?>
    <?php endif; ?>
<?php endif; ?>
