<div class="page-main-actions">
    <div class="store-switcher store-view" style="font-size:2.3rem">
        <span class="store-switcher-label">Item Category</span>
    </div>
    <div class="page-actions-placeholder" style=""></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button 
                onclick="location.href = '<?php echo $block->getUrl('giftvoucher/addnewtemplate/index'); ?>'"
                class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" data-form-role="save" data-ui-id="save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text">
                        <span>Add New Template</span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>