<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/GiftCard
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-gift-card
 */
// @codingStandardsIgnoreFile
?>
<?php
$_order  = $block->getOrder();
$_source = $block->getSource();
?>


<tr class="totals-tax">
    <th <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> scope="row">
        <?php if ($block->getNameInLayout() == 'giftcard_creditmemo'): ?>
        <?php /* @escapeNotVerified */ echo __('Refunded to Gift Card'); ?>
        <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('Gift Card Discount'); ?>
        <?php endif;?>
    </th>
    <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml(__('Gift Card Discount')); ?>">
        <?php /* @escapeNotVerified */ echo $_order->formatPrice($_source->getGiftcardAmount()) ?>
    </td>
</tr>
