<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/GiftCard
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-gift-card
 */
// @codingStandardsIgnoreFile
?>
<?php $_source  = $block->getSource() ?>
<?php if ($_source && $_source->getGiftcardAmount() != 0): ?>
    <tr>
        <td class="label"><?php /* @escapeNotVerified */ echo __('Gift Card Discount') ?></td>
        <td>
            <input type="text"
                   name="creditmemo[giftcard_amount]"
                   value="<?php /* @escapeNotVerified */ echo $_source->getGiftcardAmount()*1 ?>"
                   class="input-text admin__control-text"
                   id="giftcard_amount" />
        </td>
    </tr>
<?php endif; ?>
