<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/GiftCard
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-gift-card
 */
?>
<?php
// @codingStandardsIgnoreFile
if ($block->showForm()) :
$collection = $block->getCollection();
?>
<div class="block discount giftcard" id="block_giftcard">
    <div class="title">
        <strong id="block-giftcard-heading"><?php /* @escapeNotVerified */ echo __('Apply Gift Card') ?></strong>
    </div>
    <div class="content">
        <form id="add_gift_card_form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('giftcard/cart/add') ?>"
              method="post"
              name="add_gift_card_form">
            <?php echo $block->getBlockHtml('formkey')?>
            <input type="hidden" name="isAjax" value="false"/>
            <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="gift_card_code" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter gift card code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="gift_card_code" name="gift_card_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Enter gift card code'));?>" />
                        <div id="gift_card_code_error" class="mage-error" for="gift_card_code" generated="true"></div>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action add-giftcard primary" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply Gift Card') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Apply Gift Card') ?></span>
                        </button>
                    </div>
                </div>

            </div>
        </form>
        <?php if ($collection->getSize() > 0): ?>

        <div class="gift-card-list">
            <div class="gift-card-list-title"><?php echo __('Applied gift card codes for cart');?></div>
            <?php foreach ($collection as $giftCard):?>
            <div class="gift-card-item">
                <div class="gift-card-code"><?php echo $giftCard->getCode();?> <strong>(<?php echo $giftCard->getFormattedBalance();?>)</strong></div>
                <div class="gift-card-action"><a class="gift-card-action-remove" href="<?php echo $block->getUrl('giftcard/cart/remove', ['id' => $giftCard->getId()]);?>"><?php echo __('Remove');?></a></div>
            </div>
            <?php endforeach; ?>
        </div>

        <?php endif; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#block_giftcard": {
            "giftCardForm": {
                "giftCardConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>,
                "isAjax": false,
                "isFormOpen": <?php echo $collection->getSize()==0?'false':'true';?>
            }
        }
    }
</script>
<?php endif; ?>